apiVersion: v1
kind: Pod
metadata:
  name: env-dump
spec:
  containers:
  - name: test-busybox
    image: busybox
    command: [ "/bin/sh", "-c", "env" ] 
    env:
      - name: WHAT_NAME
        valueFrom:
          configMapKeyRef:
             name: my-map
             key: STUDENT_NAME
      - name: WHAT_SCHOOL      
        valueFrom:
          configMapKeyRef:
             name: my-map
             key: STUDENT_SCHOOL
      - name: WHAT_PROFESSION
        valueFrom:
          configMapKeyRef:
             name: my-map
             key: STUDENT_WORK

